name: OCI Latency (Hangzhou NAS)

on:
  workflow_dispatch:
    inputs:
      instance_ocid:
        description: "Target OCI instance OCID (可留空，用默认)"
        required: false
        default: ""   # 留空表示使用默认

jobs:
  check:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: python:3.11
    env:
      # 允许手动输入覆盖默认；留空则用 Secrets 中的值
      OCI_INSTANCE_ID: ${{ github.event.inputs.instance_ocid != '' && github.event.inputs.instance_ocid || secrets.OCI_INSTANCE_ID }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt-get update
          apt-get install -y iputils-ping iproute2
          pip install --no-cache-dir oci
      - run: python monitor_latency.py
        env:
          OCI_CLI_USER:        ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY:     ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_REGION:      ${{ secrets.OCI_CLI_REGION }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_PASSPHRASE:  ${{ secrets.OCI_CLI_PASSPHRASE }}
          OCI_INSTANCE_ID:     ${{ env.OCI_INSTANCE_ID }}
