name: OCI Latency (Hangzhou NAS)

on:
  workflow_dispatch:
    inputs:
      instance_ocid:
        description: "Target OCI instance OCID (可留空则用默认 Secret)"
        required: false
        default: ""

jobs:
  check:
    runs-on: [self-hosted, Linux, X64]   # 或 [self-hosted, hangzhou-nas]
    timeout-minutes: 30

    env:
      # 允许输入覆盖默认；留空就用 Secrets 里的 OCI_INSTANCE_ID
      OCI_INSTANCE_ID: ${{ github.event.inputs.instance_ocid != '' && github.event.inputs.instance_ocid || secrets.OCI_INSTANCE_ID }}

    steps:
      - name: Network warm-up
        run: |
          apt-get update
          apt-get install -y ca-certificates curl dnsutils git
          update-ca-certificates || true
          # 有些环境 HTTP/2 + GnuTLS 不稳，强制用 HTTP/1.1
          git config --global http.version HTTP/1.1
          # 先探测一遍，便于快速失败时定位
          echo "== curl github.com =="
          curl -I --max-time 10 https://github.com || true
          echo "== curl api.github.com =="
          curl -I --max-time 10 https://api.github.com || true
          echo "== DNS =="
          nslookup github.com || getent hosts github.com || true

      - name: Force SSH over 443
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" \
            "Host github.com" \
            "  HostName ssh.github.com" \
            "  Port 443" \
            "  User git" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          # 预置 known_hosts，避免握手卡住
          ssh-keyscan -p 443 ssh.github.com >> ~/.ssh/known_hosts

      - name: Checkout via SSH
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PKEY }}
          persist-credentials: false
          fetch-depth: 1

      - name: Install deps (ping + python + SDK)
        run: |
          apt-get update
          apt-get install -y iputils-ping iproute2 python3 python3-pip
          pip3 install --no-cache-dir oci

      - name: Verify OCI key file & fingerprint
        run: |
          apt-get update && apt-get install -y openssl
          # 写入你在 Secrets 里的私钥
          cat > /tmp/oci_key.pem <<'PEM'
            ${{ secrets.OCI_CLI_KEY_CONTENT }}
            PEM
          chmod 600 /tmp/oci_key.pem
          echo -n "Key header: "; head -n1 /tmp/oci_key.pem

          # 1) 如果是 OpenSSH/ed25519，直接报错
          if head -n1 /tmp/oci_key.pem | grep -q 'OPENSSH'; then
            echo "❌ 你填的是 SSH 私钥（OpenSSH），不是 OCI API 的 RSA 私钥。请去 OCI 控制台 User settings → API Keys → Add API Key → Generate，复制下载的 RSA 私钥 PEM 到 OCI_CLI_KEY_CONTENT。"
            exit 2
          fi

          # 2) 计算该私钥对应的指纹（MD5，冒号分隔）
          FP=$({ openssl rsa  -pubout -in /tmp/oci_key.pem -outform DER 2>/dev/null \
              || openssl pkey -pubout -in /tmp/oci_key.pem -outform DER 2>/dev/null; } \
              | openssl dgst -md5 -c | awk '{print $2}')
          echo "Provided fingerprint:  ${{ secrets.OCI_CLI_FINGERPRINT }}"
          echo "Computed fingerprint:  $FP"

          if [ "$FP" != "${{ secrets.OCI_CLI_FINGERPRINT }}" ]; then
            echo "❌ 指纹不匹配。请以“OCI 控制台 API Keys 页面显示的那串指纹”为准，或重新生成 API Key Pair 并同步更新私钥与指纹。"
            exit 2
          fi

      - name: Test Identity auth (get_user)
        run: |
          python3 - <<'PY'
          import os, oci
          cfg = {
            "user": os.environ["OCI_CLI_USER"],
            "tenancy": os.environ["OCI_CLI_TENANCY"],
            "region": os.environ["OCI_CLI_REGION"],
            "fingerprint": os.environ["OCI_CLI_FINGERPRINT"],
            "key_file": "/tmp/oci_key.pem",
          }
          ic = oci.identity.IdentityClient(cfg)
          u  = ic.get_user(os.environ["OCI_CLI_USER"]).data
          print("✅ Auth OK. User:", u.name, u.id)
          PY
        env:
          OCI_CLI_USER:        ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY:     ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_REGION:      ${{ secrets.OCI_CLI_REGION }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}

      - name: Run latency optimizer
        env:
          OCI_CLI_USER:        ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY:     ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_REGION:      ${{ secrets.OCI_CLI_REGION }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_PASSPHRASE:  ${{ secrets.OCI_CLI_PASSPHRASE }}
          LATENCY_THRESHOLD_MS: ${{ secrets.LATENCY_THRESHOLD_MS }}
          PING_COUNT:           ${{ secrets.PING_COUNT }}
          MAX_SWITCHES:         ${{ secrets.MAX_SWITCHES }}
          OCI_INSTANCE_ID:      ${{ env.OCI_INSTANCE_ID }}
        run: python3 monitor_latency.py
