name: OCI Latency (Hangzhou NAS)

on:
  workflow_dispatch:
    inputs:
      instance_ocid:
        description: "Target OCI instance OCID (可留空则用默认 Secret)"
        required: false
        default: ""

jobs:
  check:
    runs-on: [self-hosted, Linux, X64]   # 或 [self-hosted, hangzhou-nas]
    timeout-minutes: 30

    env:
      # 允许输入覆盖默认；留空就用 Secrets 里的 OCI_INSTANCE_ID
      OCI_INSTANCE_ID: ${{ github.event.inputs.instance_ocid != '' && github.event.inputs.instance_ocid || secrets.OCI_INSTANCE_ID }}

    steps:
      - name: Network warm-up
        run: |
          apt-get update
          apt-get install -y ca-certificates curl dnsutils git
          update-ca-certificates || true
          # 有些环境 HTTP/2 + GnuTLS 不稳，强制用 HTTP/1.1
          git config --global http.version HTTP/1.1
          # 先探测一遍，便于快速失败时定位
          echo "== curl github.com =="
          curl -I --max-time 10 https://github.com || true
          echo "== curl api.github.com =="
          curl -I --max-time 10 https://api.github.com || true
          echo "== DNS =="
          nslookup github.com || getent hosts github.com || true

      - name: Force SSH over 443
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" \
            "Host github.com" \
            "  HostName ssh.github.com" \
            "  Port 443" \
            "  User git" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          # 预置 known_hosts，避免握手卡住
          ssh-keyscan -p 443 ssh.github.com >> ~/.ssh/known_hosts

      - name: Checkout via SSH
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.PKEY }}
          persist-credentials: false
          fetch-depth: 1

      - name: Install deps (ping + python + SDK)
        run: |
          apt-get update
          apt-get install -y iputils-ping iproute2 python3 python3-pip
          pip3 install --no-cache-dir oci

      - name: Verify OCI key & fingerprint
        run: |
          apt-get update && apt-get install -y openssl
          # 把 Secrets 里的私钥写到文件
          cat > /tmp/oci_key.pem <<'PEM'
            ${{ secrets.OCI_CLI_KEY_CONTENT }}
            PEM
          chmod 600 /tmp/oci_key.pem

          echo -n "Key header: "; head -n1 /tmp/oci_key.pem
          if head -n1 /tmp/oci_key.pem | grep -q 'OPENSSH'; then
            echo "❌ 你填的是 SSH 私钥（OpenSSH/ed25519），不是 OCI API 的 RSA 私钥。请用控制台生成的私钥（BEGIN PRIVATE KEY）。"
            exit 2
          fi

          # 从私钥导出公钥并计算 MD5 指纹（冒号分隔）
          FP=$({ openssl rsa  -pubout -in /tmp/oci_key.pem -outform DER 2>/dev/null \
              || openssl pkey -pubout -in /tmp/oci_key.pem -outform DER 2>/dev/null; } \
              | openssl dgst -md5 -c | awk '{print $2}')
          echo "Provided fingerprint:  ${{ secrets.OCI_CLI_FINGERPRINT }}"
          echo "Computed fingerprint:  $FP"

          if [ "$FP" != "${{ secrets.OCI_CLI_FINGERPRINT }}" ]; then
            echo "❌ 指纹与这把私钥不匹配。请以控制台 API Keys 页显示的指纹为准，或删除旧 Key 重新 Generate 一套并同时更新指纹与私钥。"
            exit 2
          fi

      - name: Test Identity auth (get_user)
        run: |
          python3 - <<'PY'
          import os, oci
          cfg = {
            "user": os.environ["OCI_CLI_USER"],
            "tenancy": os.environ["OCI_CLI_TENANCY"],
            "region": os.environ["OCI_CLI_REGION"],
            "fingerprint": os.environ["OCI_CLI_FINGERPRINT"],
            "key_file": "/tmp/oci_key.pem",
          }
          ic = oci.identity.IdentityClient(cfg)
          u  = ic.get_user(os.environ["OCI_CLI_USER"]).data
          print("✅ Auth OK. User:", u.name, u.id)
          PY
        env:
          OCI_CLI_USER:        ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY:     ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_REGION:      ${{ secrets.OCI_CLI_REGION }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}

      - name: Run latency optimizer
        env:
          OCI_CLI_USER:        ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY:     ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_REGION:      ${{ secrets.OCI_CLI_REGION }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_PASSPHRASE:  ${{ secrets.OCI_CLI_PASSPHRASE }}

          # 行为参数（可不设）
          LATENCY_THRESHOLD_MS: ${{ (secrets.LATENCY_THRESHOLD_MS != '' && secrets.LATENCY_THRESHOLD_MS) || '80' }}
          PING_COUNT:           ${{ (secrets.PING_COUNT           != '' && secrets.PING_COUNT)           || '3'  }}
          MAX_SWITCHES:         ${{ (secrets.MAX_SWITCHES         != '' && secrets.MAX_SWITCHES)         || '10' }}
          SLEEP_BETWEEN_SWITCH_S: ${{ (secrets.SLEEP_BETWEEN_SWITCH_S != '' && secrets.SLEEP_BETWEEN_SWITCH_S) || '6' }}
          TCP_FALLBACK_PORT:    ${{ (secrets.TCP_FALLBACK_PORT    != '' && secrets.TCP_FALLBACK_PORT)    || '22' }}

          # Telegram
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}

          # 实例 OCID（可用默认 Secret，也可用 inputs 覆盖）
          OCI_INSTANCE_ID: ${{ env.OCI_INSTANCE_ID }}
        run: python3 monitor_latency.py
