name: NAS runner smoke test
on: workflow_dispatch
jobs:
  test:
    runs-on: [self-hosted, Linux, X64]  # 或 [self-hosted, hangzhou-nas]
    steps:
      - name: Basic info
        run: |
          echo "Hello from $(hostname)"
          uname -a
          id
      - name: Show network addresses (best effort)
        run: |
          if command -v ip >/dev/null 2>&1; then
            ip -br addr
          elif command -v ifconfig >/dev/null 2>&1; then
            ifconfig
          else
            echo "Installing iproute2 (Debian/Ubuntu)..."
            (apt-get update && apt-get install -y iproute2) || true
            command -v ip >/dev/null && ip -br addr || echo "no ip/ifconfig; skip"
          fi
