name: NAS runner smoke test
on: workflow_dispatch
jobs:
  test:
    runs-on: [self-hosted, hangzhou-nas]  # 先别加 linux/x64，避免标签不一致
    steps:
      - run: |
          echo "Hello from $(hostname)"
          uname -a
          id
