# .github/workflows/smoke.yml
name: NAS runner smoke test
on: workflow_dispatch
jobs:
  test:
    runs-on: [self-hosted, Linux, X64]   # ← 或者更简单：runs-on: self-hosted
    steps:
      - run: |
          echo "Hello from $(hostname)"
          uname -a
          id
          ip -br addr
